### ISSUE TITLE
Ordre

### ISSUE THREAD

**Issue by LorgneSchilooch** [rypall/yamlDataBase#11]
https://github.com/rypall/yamlDataBase/blob/793a4855db61ae8930422806a141d40c6c0e9623/sources/c/system_function.c#L31

Ne devrait on pas vérifier en premier que la base existe dans le fichier YAML ?
Ou ne pas faire appel au changement de base si ce n'est qu'une fonction qui retourne une info ?

**Comment by Pi5rr5** [comment]
Comme la base courante sera une global ou un fonction type get/set il n'y a pas besoin de fonction useDB coté système mais plutôt une fontion isExistDB(), déjà implem.
https://github.com/rypall/yamlDataBase/blob/4d1028639bf81204a34b395a5259d04661a5c831/sources/h/system_function.h#L6
