### ISSUE TITLE
master build failt

### ISSUE THREAD

**Issue by Pi5rr5** [rypall/yamlDataBase#22]
||=== Build: Debug in yamlDataBase (compiler: GNU GCC Compiler) ===|
D:\yamlDataBase\sources\c\Core.c||In function 'query_use':|
D:\yamlDataBase\sources\c\Core.c|16|warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]|
D:\yamlDataBase\sources\c\Core.c|16|warning: passing argument 2 of 'countArgs' makes pointer from integer without a cast [-Wint-conversion]|
d:\yamldatabase\sources\h\some_funct.h|16|note: expected 'const char *' but argument is of type 'char'|
D:\yamlDataBase\sources\c\Core.c|18|warning: implicit declaration of function 'getBlockWhere' [-Wimplicit-function-declaration]|
D:\yamlDataBase\sources\c\Core.c|18|warning: comparison between pointer and integer|
D:\yamlDataBase\sources\c\Core.c|19|warning: implicit declaration of function 'useDB' [-Wimplicit-function-declaration]|
D:\yamlDataBase\sources\c\Core.c|20|warning: implicit declaration of function 'changeDatabase' [-Wimplicit-function-declaration]|
D:\yamlDataBase\sources\c\Core.c|20|error: 'dbName' undeclared (first use in this function)|
D:\yamlDataBase\sources\c\Core.c|20|note: each undeclared identifier is reported only once for each function it appears in|
D:\yamlDataBase\sources\c\Core.c||In function 'query_create_database':|
D:\yamlDataBase\sources\c\Core.c|37|warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]|
D:\yamlDataBase\sources\c\Core.c|37|warning: passing argument 2 of 'countArgs' makes pointer from integer without a cast [-Wint-conversion]|
d:\yamldatabase\sources\h\some_funct.h|16|note: expected 'const char *' but argument is of type 'char'|
D:\yamlDataBase\sources\c\Core.c|39|warning: implicit declaration of function 'funcyaml' [-Wimplicit-function-declaration]|
D:\yamlDataBase\sources\c\Core.c||In function 'query_drop_database':|
D:\yamlDataBase\sources\c\Core.c|58|warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]|
D:\yamlDataBase\sources\c\Core.c|58|warning: passing argument 2 of 'countArgs' makes pointer from integer without a cast [-Wint-conversion]|
d:\yamldatabase\sources\h\some_funct.h|16|note: expected 'const char *' but argument is of type 'char'|
D:\yamlDataBase\sources\c\Core.c||In function 'query_drop_table':|
D:\yamlDataBase\sources\c\Core.c|79|warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]|
D:\yamlDataBase\sources\c\Core.c|79|warning: passing argument 2 of 'countArgs' makes pointer from integer without a cast [-Wint-conversion]|
d:\yamldatabase\sources\h\some_funct.h|16|note: expected 'const char *' but argument is of type 'char'|
D:\yamlDataBase\sources\c\Core.c|82|error: too few arguments to function 'dropTable'|
d:\yamldatabase\sources\h\system_function.h|10|note: declared here|
D:\yamlDataBase\sources\c\Core.c||In function 'query_create_table':|
D:\yamlDataBase\sources\c\Core.c|110|error: too few arguments to function 'createTable'|
d:\yamldatabase\sources\h\system_function.h|8|note: declared here|
D:\yamlDataBase\sources\c\Core.c||In function 'goSplitCreateQuery':|
D:\yamlDataBase\sources\c\Core.c|152|warning: unused variable 'name' [-Wunused-variable]|
D:\yamlDataBase\sources\c\Core.c|151|warning: unused variable 'token1' [-Wunused-variable]|
||=== Build failed: 3 error(s), 15 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/c/Core.c#L20
dbName pas déclaré

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/c/Core.c#L82
dropTable prend 2 params, tableName et dbName, si une globale current_db_name à été crée la passer en param

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/c/Core.c#L110
pareil que pour dropTable

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/c/Core.c#L151
D:\yamlDataBase\sources\c\Core.c|151|warning: ___unused variable 'token1'___ [-Wunused-variable]|

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/c/Core.c#L16
D:\yamlDataBase\sources\c\Core.c|16|warning: ___passing argument 2 of 'countArgs'___ makes pointer from integer without a cast [-Wint-conversion]|
https://github.com/rypall/yamlDataBase/blob/a32ceaf39a5713e19669900d23813bf5817e2e9f/sources/h/some_funct.h#L16

**Comment by LorgneSchilooch** [comment]
Si tu changes tes fonctions sans l'indiquer dans les issues qui les demandes. Je ne peux pas faire de miracle malheureusement. Pour le reste je regarde ce soir mais je n'ai pas le problème avec CountArgs.

Il serait plus simple d'ouvrir des issues pour chaque problème afin d'avoir un suivi.

**Comment by rypall** [comment]
Je t'invite à prendre le temps de regarder les pulls request ou master. Car il me semble que cela était push, pull request puis merge avant. Ou encore la chat discord, certaines des fonctions prennent le nom de la bases courante en attendant d'avoir une globale.

**Comment by LorgneSchilooch** [comment]
Je viens de zieuter, je n'ai vu aucun commentaire dans les pushs ou merge indiquant les changements.
Il faut communiquer si tu changes des fonctions qui ont un impact ailleurs...

**Comment by rypall** [comment]
Oublie pas discord j'ai communiqué dessus ;)
De plus c'est pas dans ce sens là qu'on avance, c'est plutôt à toi de regarder ce qui a changé avant d'implémenter ta partie car au jour où j'ai implem celà ne posait aucun soucis.

**Comment by rypall** [comment]
https://github.com/rypall/yamlDataBase/blob/4d1028639bf81204a34b395a5259d04661a5c831/sources/c/system_function.c#L42
kappa

**Comment by LorgneSchilooch** [comment]
@rypall Merci de nous expliquer pourquoi ces ajouts d'arguments sur ces fonctions. Sans ça on ne peut pas avancer.

**Comment by rypall** [comment]
Ça a été fait.

**Comment by LorgneSchilooch** [comment]
redonne le nous alors, car on ne sait pas !

**Comment by rypall** [comment]
*le discord

**Comment by LorgneSchilooch** [comment]
Bon, je te laisse faire tes modifs, je ne touche pas à rien sans explication. Réveille toi, on est deux à ne pas savoir pourquoi tu as modifié tes fonctions en ajoutant cet argument

**Comment by HugoESGI** [comment]
J'ai pas tout suivis. Alors je vais faire reprendre à zéro : Pierre est-ce que tu considère les fonctions système comme finie à 100% ? Si oui, est-ce que l'on peut débattre sur de potentiel modifications ? Sinon, quels ont été tes raisonnement, pas pour tout le code, juste pour le choix de passé le nom de la bdd en paramètre et pas passer par l'utilisation d'une globale dont nous avions, il me semblais, avoir convenu ?

**Comment by rypall** [comment]
Alors Hugo je pense que tu as pas suivi ou je ne te comprend pas on en a parlé après que je push tous ça vous ne regardez pas les modifs ça fait 10-15 jours que c'est comme ça. Il me semble qu'on en a parlé que je t'ai expliqué que c'était en attendant d'avoir une autre solution qui est la globale. Faut juste faire le faire mais faudrait suivre un peu toute pull request et message sur discord car c'est des faux débats à répétition pour dire la même chose

**Comment by rypall** [comment]
Vraiment faut être ouvert d'esprit et lire le code j'écris en clair TODO au dessus de la fonction. Et quand je dis ouvert d'esprit c'est mais putain si tu veux la chose fais le sur une branch fais la pull request et après on regarde. Vous connaissez le travail de groupe sur les projet open source comment ça marche ou pas ?

**Comment by rypall** [comment]
Donc pour te répondre Hugo, de façon simple, non quand je laisse des TODO et qu'on parle de modif à faire ce n'est pas finie à 100% comme tous le reste et si on continue avec des faux débats comme ça je sais pas ce que vous comptez rendre dans environ 4 jours

**Comment by rypall** [comment]
Et Olivier vraiment tu es culotté de te plaindre de pas savoir des choses quand tu rage quit le discord comme un enfant on va dire les choses au bout d'un moment

**Comment by HugoESGI** [comment]
Mais comment ça "attendre d'avoir une solution qui est globale", "TODO". C'est tes fonctions, fais le non ? Pourquoi attendre ? Et je te rappelles que ni Olivier ni moi ne sommes à l'aise avec Git/GitHub et les notions de pull request. Si il y a qqchose d'important à faire passer mieux vaut le dire en clair plutôt que de le mettre en ligne de ocmmentaire dans ton code en espérant qu'on tombe dessus.
Sinon pour avancer sur autre chose : l'interface graphique, quand est-ce que tu voudras qu'on l'implémente ?

**Comment by rypall** [comment]
C'est dingue de devoir ce justifier comme ça.
Je vais te sortir les screen DISCORD J'AI BIEN DIT DISCORD, dans lesquels je te dit pourquoi c'est comme ça !
Et je pense pas que ce soit le lieu de parler de l'interface. Ici c'est fix master qui build pas.
Pour l'interface j'ai post un gif + une branch.

**Comment by HugoESGI** [comment]
On peut parler sur les branches O.o ?
Anyway, discord ça se rempli, les messages ça se perd, ça s'oublie. Tu peux juste nous rappeler les pourquoi du comment ça va pas te tuer. Tu comprends bien qu'on taff de notre coté et qu'on a pas que ça a faire que de scroll Discord quand même.

**Comment by rypall** [comment]
Et les mecs vraiment je sais pas comment est votre façon de travailler mais habitué vous à ça, vraiment c'est grave d'avoir une peur de faire comme ça tu dis "c'est tes fonctions" mais non c'est celle du projet donc les tiennes alors ok je t'explique comment elle marche si tu comprends pas mais si tu veux autre chose fais le et on avance plutôt que débattre pour rien je ne répondrai plus que sur discord comme vous n'êtes pas familier GitHub ;)

**Comment by HugoESGI** [comment]
Mais... On se réparti des tâches, on a chacun nos parties. Si notre partie n'est pas finie on ne pas venir mettre le bazar dans celle des autres. Si qqchose nous interpèle on te demande, tu réponds, on communiques, tout ça tout ça. Mais cloturer la conversation par des "je l'ai déjà dit sur Discord"... meh. Fin bref, je vais tourner le truc autrement maintenant : Olivier est pris par le parser SQL et moi même par le YAML. J'ai, personellement, pris du retard sur ce que je fais. J'en suis désolé. Et devant rattrapper ce retard et Olivier n'étant pas disponible, est-ce que tu pourrais implémenter le système de globale pour le nom de la base de donnée ? Si tu es contre ce concept nous serons ravi d'entendre tes arguments sur le sujet.  Et si tu ne veux pas, ba tant pis, je le ferai quand j'aurais fini ma partie.

**Comment by rypall** [comment]
Vraiment un conseil pour toi dans ta vie de dev regarde les projet open source exemple Angular ;)
Pour le reste te ne comprends pas je suis ok pour l'implantation, donc ok ok et ok ;)

**Comment by rypall** [comment]
Mais c'est un faux débats ___ICI___ car ici c'est juste fix le master.

**Comment by HugoESGI** [comment]
Ba ouvre une conversation appropriée alors. "Fais le toi même" tu me dirais. Mais je ne savais pas que c'était aussi important de respecter les emplacement de débat quand on est trois sur le projet...

**Comment by rypall** [comment]
C'est plutôt que après on risque de me dire mais où tu l'as dis je sais pas blabla ;)

**Comment by rypall** [comment]
solved :poop:
