### ISSUE TITLE
doublon

### ISSUE THREAD

**Issue by LorgneSchilooch** [rypall/yamlDataBase#5]
La structure semble erronée. elle contient deux fois sa propre structure

https://github.com/rypall/yamlDataBase/blob/1b5ae8f278b832eef6f8d63b80c7a7fcd36e8c8a/sources/h/struct.h#L48

**Comment by Pi5rr5** [comment]
non c'est une liste chainé de structure

**Comment by LorgneSchilooch** [comment]
corrigé par @HugoESGI
