### ISSUE TITLE
Includes

### ISSUE THREAD

**Issue by HugoESGI** [rypall/yamlDataBase#8]
Pensez à bien inclure toutes les librairies (stdio, stdlib et string).
```C
#include <stdio.h>

#include "../h/some_funct.h"
#include "../h/parser_SQL.h"
```

**Comment by rypall** [comment]
Cette issue vient d'où ?

**Comment by HugoESGI** [comment]
Elle est générale, Olivier m'a dit de regarder son code et sur certains fichiers il manquait des includes. Alors j'ai créer cette issue.

**Comment by rypall** [comment]
Plutôt que de créer l'issue quand tu vois un manque d'include ajoutes les directement depuis github rapide et efficace ;) Car là on sait pas où tu as vu ça ..

**Comment by HugoESGI** [comment]
O.o mais alors à quoi servent les issues si on modifie le code des autres directement ?

**Comment by HugoESGI** [comment]
Oops mauvais bouton

**Comment by rypall** [comment]
Quand on à un doute ou qu'on est pas capable de corriger ou encore qu'on ne sait pas comment corriger mais qu'il y a une issue 😄

**Comment by HugoESGI** [comment]
Aaaaaaah ok, c'est noté.

**Comment by HugoESGI** [comment]
Mais ça ne pose pas de problème de modifier le code de qqn d'autre ? Il est averti ou c'est à nous de le faire ?

**Comment by rypall** [comment]
Non pas quand c'est quelque chose comme ça, enfin je pense pas. Et oui il est averti de un et deuxièment tous est versionné alors on peut annuler des modifs facilement 👀

**Comment by HugoESGI** [comment]
Okok
